"""empty message

Revision ID: b3f1636d875c
Revises: 
Create Date: 2019-10-21 11:52:24.759452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f1636d875c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('duration', sa.String(length=128), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=128), nullable=True),
    sa.Column('full_image_url', sa.String(length=128), nullable=True),
    sa.Column('downloaded_thumbnail_path', sa.String(length=128), nullable=True),
    sa.Column('downloaded_full_image_path', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    # ### end Alembic commands ###
